# Generated by Django 3.2.12 on 2022-04-23 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_texto', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filme_ou_serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme_texto', models.CharField(max_length=200)),
                ('filme_ranking_critica', models.IntegerField(default=0)),
                ('filme_ranking_audiencia', models.IntegerField(default=0)),
                ('filme_descricao', models.CharField(max_length=2000)),
                ('is_filme', models.IntegerField(default=0)),
                ('pub_data', models.DateTimeField(verbose_name='data de publicacao')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='questao',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
        migrations.DeleteModel(
            name='Questao',
        ),
        migrations.AddField(
            model_name='filme_ou_serie',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.genero'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='identificador_conteudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.filme_ou_serie'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
