# Generated by Django 3.2.12 on 2022-05-01 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0003_auto_20220423_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='critico',
            name='imagem',
            field=models.CharField(default='0000000', max_length=300),
        ),
        migrations.AddField(
            model_name='filme_ou_serie',
            name='imagem',
            field=models.CharField(default='0000000', max_length=300),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(default='0000000', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
