# Generated by Django 3.2.12 on 2022-05-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_auto_20220501_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme_ou_serie',
            old_name='genero',
            new_name='genero_id',
        ),
    ]
