# Generated by Django 3.2.12 on 2022-05-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_rename_genero_filme_ou_serie_genero_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenero2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='filme_ou_serie',
            name='release_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario_texto',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='filme_ou_serie',
            name='filme_descricao',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='filme_ou_serie',
            name='genero_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='votacao.genero'),
        ),
        migrations.AddField(
            model_name='filme_ou_serie',
            name='subgenero2_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='votacao.subgenero2'),
        ),
        migrations.AddField(
            model_name='filme_ou_serie',
            name='subgenero_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='votacao.subgenero'),
        ),
    ]
