# Generated by Django 3.2.12 on 2022-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0006_auto_20220502_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme_ou_serie',
            name='trailer',
            field=models.CharField(default=0, max_length=3000),
        ),
    ]
