# Generated by Django 3.2.12 on 2022-05-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0007_filme_ou_serie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme_ou_serie',
            name='atores',
            field=models.CharField(default=0, max_length=3000),
        ),
    ]
