# Generated by Django 3.2.12 on 2022-05-09 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votacao', '0008_filme_ou_serie_atores'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacao.filme_ou_serie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
