# Generated by Django 3.2.12 on 2022-05-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0012_auto_20220513_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme_ou_serie',
            name='filme_ranking_critica',
            field=models.IntegerField(default=0),
        ),
    ]
